### ISSUE TITLE
Select and Remove a Feature

### ISSUE THREAD

**Issue by rvrtester** [mapbender/mapbender-digitizer#15]
When you select and remove a feature in Mapbender (per "Select Geometry" + "Remove selected Geometry") you have to open the feature dialog another time to save the action.

But if you click on "Save" (in the feature dialog) the application freezes.

It would be nice, that after "Remove selected Geometry" the feature is deleted directly.

**Comment by AxxL** [comment]
Can you tell again the workflow step by step? There are some ways to delete a feature (button, table, right-click), so that we know which one you meant.

Right now I cannot reproduce this specific issue (by using the toolbar button), especially the "save" one.

1. Toolbar button: remove
2. Click on feature
3. dialog opens.
4a: Delete: deletes feature, after extra confirmation popup (OK)
4b: Save: saves feature (OK)

Testet on: http://release.mapbender3.org/application/mapbender_digitize_demo

**Comment by rvrtester** [comment]
The workflow step by step:

 1. Click on "Select geometry" (the button from the toolbar - between the buttons "Move geometry" and "Remove selected geometries")
 2. Select a feature, say Object-Nr. 168 with the name "Test" (located at Hofgarten in Bonn). The selected feature will be highlighted...
 3. Click on "Remove selected geometries". The selected feature disappears from the map, but the entry in the table is still there...
 4. Click on "Edit feature" for Object-Nr. 168. Nothing happens... (in my installation the attribute dialog opens...)
 5. After a refresh of the application, Object-Nr. 168 is visible on the map again... (...and not removed)
 
My suggestion is, that (3) should look like this:

 3. Click on "Remove selected geometries". The selected feature disappears from the map. The entry disappears from the table. Object-Nr. 168 is removed (in the database).

**Comment by AxxL** [comment]
@rvrtester Thanks.

**Comment by AxxL** [comment]
In Digitizer 1.1.x

Select a geometry. The features in the table are not selected. The selection in unselected in the display if I hover on a feature. The entries in the table are only highlighted if I hover with the mouse over a feature.

Expected behaviour:

* If I select the items, they should be selected also in the table.
* If I hover with the mouse, the selection should not be changed.

If I have the delete button also configured, it should be possible to delete the selected features.

* Fix the delete-functionality: Right now the feature cannot be deleted.
* Adjust the workflow of the delete functionality with the select geometries feature.

**Comment by astroidex** [comment]
select and remove are not supported in Mapbender 4

**Comment by astroidex** [comment]
select and remove are not supported in Mapbender 4
